### ISSUE TITLE
Codici stazioni italiane

### ISSUE THREAD

**Issue by federicomarollatouch** [SimoDax/Italo-API#4]
Ciao, sarebbe possibile recuperare tutte le stazioni disponibili in Italia? La lista nella documentazione purtroppo contiene solo le stazioni più importanti. Esiste un API che possa tirarle giù con relativi codici?
@SimoDax la lista iniziale da dove sei riuscito a tirarla giù?

Grazie mille

**Comment by SimoDax** [comment]
Ciao

L'elenco stazioni è recuperabile da qui https://www.italotreno.it/api/getStations?includeWhiteLabel=true&lang=it&ntvAjaxControlAction=getStations

Vanno filtrate per isItalo: true (non ho idea di cosa se ne fanno di tutte le altre, tanto la velocità di caricamento del sito non è loro problema..)

**Comment by federicomarollatouch** [comment]
> Ciao
> 
> L'elenco stazioni è recuperabile da qui https://www.italotreno.it/api/getStations?includeWhiteLabel=true&lang=it&ntvAjaxControlAction=getStations
> 
> Vanno filtrate per isItalo: true (non ho idea di cosa se ne fanno di tutte le altre, tanto la velocità di caricamento del sito non è loro problema..)

Grande, grazie mille
